repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: 'Run ruff format'
        types: [python]
        language: system
        entry: uv run ruff format
      # ruff-format/ END

      - id: ruff-check
        name: 'Run ruff check'
        types: [python]
        language: system
        entry: uv run ruff check
      # ruff-check/ END
    # hooks/ END
  # local/ END
# repos/ END
