name: 'EP/readit/enqueue'

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to enqueue'
        required: true
      # url/ END
    # inputs/ END
  # workflow_dispatch/ END
# on/ END

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 'Show input url'
        run: echo '${{ github.event.inputs.url }}'

      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7
        with:
          version: 0.9.22 # Latest as of 2026 Jan 07
        # with/ END

      - name: 'Install cikit'
        run: uv tool install --force ./.github/cikit
      - name: 'Install server'
        run: uv tool install --force ./server

      - name: 'Create endpoint.config.toml'
        env:
          GIST_DOWNLOAD_TOKEN: ${{ secrets.TOKEN }}
          GIST_URL: ${{ secrets.CONFIG_GIST_URL }}
        run: cikit download-gist -o endpoint.config.toml "$GIST_URL/prod.toml"

      - name: 'Enqueue'
        env:
          OWNER_TOKEN: ${{ secrets.TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          endpoint readit enqueue '${{ github.event.inputs.url }}'
          endpoint-readit-send-to-personal '${{ github.event.inputs.url }}'
          endpoint-readit-send-to-queue-v2 '${{ github.event.inputs.url }}'
        continue-on-error: true
        # 'continue-on-error' ensures that a failure from one command not to affect the others
    # steps/ END
  # run/ END
# jobs/ END
